In [ ]:
import pandas as pd

In [12]:
df = pd.read_excel("Egyptian_Grocery_Transactions.xlsx" , header=None)

In [13]:
df

                                     0
0                          سكر,لبن,شاي
1                           فراخ,بطاطس
2                              رز,فراخ
3                    عسل,لحمة,رز,زبادي
4                           بصل,رز,عدس
5                شيبسي,فلفل,بيبسي,مياه
6                     فراخ,بطاطس,شيبسي
7                 طماطم,عدس,كورن فليكس
8                عسل,مربة,زيت,عيش بلدي
9        فراخ,مكرونة,شاي,كشري,سكر,سمنة
10                             عسل,عدس
11   زيت,بيض,فول,مكرونة,صلصة,جبنة قريش
12           شاي,عدس,عسل,زيت,بيبسي,بيض
13                         رز,عدس,كشري
14                       كشري,عيش بلدي
15                      لبن,بيبسي,مربة
16                 سكر,عيش بلدي,مكرونة
17                   بيبسي,زبادي,طعمية
18           بيبسي,سكر,زيت,عدس,فول,بيض
19  بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش

In [19]:
df.values

array([['سكر,لبن,شاي'],
       ['فراخ,بطاطس'],
       ['رز,فراخ'],
       ['عسل,لحمة,رز,زبادي'],
       ['بصل,رز,عدس'],
       ['شيبسي,فلفل,بيبسي,مياه'],
       ['فراخ,بطاطس,شيبسي'],
       ['طماطم,عدس,كورن فليكس'],
       ['عسل,مربة,زيت,عيش بلدي'],
       ['فراخ,مكرونة,شاي,كشري,سكر,سمنة'],
       ['عسل,عدس'],
       ['زيت,بيض,فول,مكرونة,صلصة,جبنة قريش'],
       ['شاي,عدس,عسل,زيت,بيبسي,بيض'],
       ['رز,عدس,كشري'],
       ['كشري,عيش بلدي'],
       ['لبن,بيبسي,مربة'],
       ['سكر,عيش بلدي,مكرونة'],
       ['بيبسي,زبادي,طعمية'],
       ['بيبسي,سكر,زيت,عدس,فول,بيض'],
       ['بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش']], dtype=object)

In [ ]:
df.values.tolist()

[['سكر,لبن,شاي'],
 ['فراخ,بطاطس'],
 ['رز,فراخ'],
 ['عسل,لحمة,رز,زبادي'],
 ['بصل,رز,عدس'],
 ['شيبسي,فلفل,بيبسي,مياه'],
 ['فراخ,بطاطس,شيبسي'],
 ['طماطم,عدس,كورن فليكس'],
 ['عسل,مربة,زيت,عيش بلدي'],
 ['فراخ,مكرونة,شاي,كشري,سكر,سمنة'],
 ['عسل,عدس'],
 ['زيت,بيض,فول,مكرونة,صلصة,جبنة قريش'],
 ['شاي,عدس,عسل,زيت,بيبسي,بيض'],
 ['رز,عدس,كشري'],
 ['كشري,عيش بلدي'],
 ['لبن,بيبسي,مربة'],
 ['سكر,عيش بلدي,مكرونة'],
 ['بيبسي,زبادي,طعمية'],
 ['بيبسي,سكر,زيت,عدس,فول,بيض'],
 ['بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش']]

In [ ]:
df.columns = ['items']

In [32]:
transactions = df['items'].str.split(',').tolist()

In [33]:
transactions

[['سكر', 'لبن', 'شاي'],
 ['فراخ', 'بطاطس'],
 ['رز', 'فراخ'],
 ['عسل', 'لحمة', 'رز', 'زبادي'],
 ['بصل', 'رز', 'عدس'],
 ['شيبسي', 'فلفل', 'بيبسي', 'مياه'],
 ['فراخ', 'بطاطس', 'شيبسي'],
 ['طماطم', 'عدس', 'كورن فليكس'],
 ['عسل', 'مربة', 'زيت', 'عيش بلدي'],
 ['فراخ', 'مكرونة', 'شاي', 'كشري', 'سكر', 'سمنة'],
 ['عسل', 'عدس'],
 ['زيت', 'بيض', 'فول', 'مكرونة', 'صلصة', 'جبنة قريش'],
 ['شاي', 'عدس', 'عسل', 'زيت', 'بيبسي', 'بيض'],
 ['رز', 'عدس', 'كشري'],
 ['كشري', 'عيش بلدي'],
 ['لبن', 'بيبسي', 'مربة'],
 ['سكر', 'عيش بلدي', 'مكرونة'],
 ['بيبسي', 'زبادي', 'طعمية'],
 ['بيبسي', 'سكر', 'زيت', 'عدس', 'فول', 'بيض'],
 ['بيض', 'بيبسي', 'طعمية', 'سكر', 'سمنة', 'جبنة قريش']]

In [43]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [44]:
t1 = TransactionEncoder()
trans = t1.fit_transform(transactions)

df_encoded = pd.DataFrame(data=trans , columns=t1.columns_)

In [45]:
df_encoded

,بصل,بطاطس,بيبسي,بيض,جبنة قريش,رز,زبادي,زيت,سكر,سمنة,...,فراخ,فلفل,فول,كشري,كورن فليكس,لبن,لحمة,مربة,مكرونة,مياه
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,True,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
6,False,True,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,True,True,...,True,False,False,True,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,True,True,False,False,True,False,False,...,False,False,True,False,False,False,False,False,True,False
12,False,False,True,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
15,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
16,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
17,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,False,False,False,True,True,False,...,False,False,True,False,False,False,False,False,False,False
19,False,False,True,True,True,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False

In [46]:
support = apriori(df_encoded , min_support=0.1, use_colnames=True )
support

    support                           itemsets
0      0.10                 frozenset({بطاطس})
1      0.30                 frozenset({بيبسي})
2      0.20                   frozenset({بيض})
3      0.10             frozenset({جبنة قريش})
4      0.20                    frozenset({رز})
5      0.10                 frozenset({زبادي})
6      0.20                   frozenset({زيت})
7      0.25                   frozenset({سكر})
8      0.10                  frozenset({سمنة})
9      0.15                   frozenset({شاي})
10     0.10                 frozenset({شيبسي})
11     0.10                 frozenset({طعمية})
12     0.30                   frozenset({عدس})
13     0.20                   frozenset({عسل})
14     0.15              frozenset({عيش بلدي})
15     0.20                  frozenset({فراخ})
16     0.10                   frozenset({فول})
17     0.15                  frozenset({كشري})
18     0.10                   frozenset({لبن})
19     0.10                  frozenset({مربة})
20     0.15                frozenset({مكرونة})
21     0.10           frozenset({بطاطس, فراخ})
22     0.15            frozenset({بيبسي, بيض})
23     0.10            frozenset({بيبسي, زيت})
24     0.10            frozenset({بيبسي, سكر})
25     0.10          frozenset({بيبسي, طعمية})
26     0.10            frozenset({بيبسي, عدس})
27     0.10        frozenset({جبنة قريش, بيض})
28     0.15              frozenset({زيت, بيض})
29     0.10              frozenset({سكر, بيض})
30     0.10              frozenset({عدس, بيض})
31     0.10              frozenset({فول, بيض})
32     0.10               frozenset({رز, عدس})
33     0.10              frozenset({عدس, زيت})
34     0.10              frozenset({عسل, زيت})
35     0.10              frozenset({فول, زيت})
36     0.10             frozenset({سمنة, سكر})
37     0.10              frozenset({شاي, سكر})
38     0.10           frozenset({مكرونة, سكر})
39     0.10              frozenset({عسل, عدس})
40     0.10       frozenset({زيت, بيبسي, بيض})
41     0.10       frozenset({بيبسي, سكر, بيض})
42     0.10       frozenset({بيبسي, عدس, بيض})
43     0.10       frozenset({بيبسي, عدس, زيت})
44     0.10         frozenset({زيت, عدس, بيض})
45     0.10         frozenset({زيت, فول, بيض})
46     0.10  frozenset({زيت, بيبسي, عدس, بيض})

In [47]:
support.sort_values('support', ascending= False)

    support                           itemsets
1      0.30                 frozenset({بيبسي})
12     0.30                   frozenset({عدس})
7      0.25                   frozenset({سكر})
6      0.20                   frozenset({زيت})
13     0.20                   frozenset({عسل})
2      0.20                   frozenset({بيض})
4      0.20                    frozenset({رز})
15     0.20                  frozenset({فراخ})
14     0.15              frozenset({عيش بلدي})
17     0.15                  frozenset({كشري})
9      0.15                   frozenset({شاي})
20     0.15                frozenset({مكرونة})
22     0.15            frozenset({بيبسي, بيض})
28     0.15              frozenset({زيت, بيض})
0      0.10                 frozenset({بطاطس})
11     0.10                 frozenset({طعمية})
10     0.10                 frozenset({شيبسي})
8      0.10                  frozenset({سمنة})
5      0.10                 frozenset({زبادي})
3      0.10             frozenset({جبنة قريش})
18     0.10                   frozenset({لبن})
19     0.10                  frozenset({مربة})
16     0.10                   frozenset({فول})
21     0.10           frozenset({بطاطس, فراخ})
23     0.10            frozenset({بيبسي, زيت})
25     0.10          frozenset({بيبسي, طعمية})
24     0.10            frozenset({بيبسي, سكر})
26     0.10            frozenset({بيبسي, عدس})
27     0.10        frozenset({جبنة قريش, بيض})
29     0.10              frozenset({سكر, بيض})
30     0.10              frozenset({عدس, بيض})
31     0.10              frozenset({فول, بيض})
32     0.10               frozenset({رز, عدس})
33     0.10              frozenset({عدس, زيت})
34     0.10              frozenset({عسل, زيت})
35     0.10              frozenset({فول, زيت})
36     0.10             frozenset({سمنة, سكر})
37     0.10              frozenset({شاي, سكر})
38     0.10           frozenset({مكرونة, سكر})
39     0.10              frozenset({عسل, عدس})
40     0.10       frozenset({زيت, بيبسي, بيض})
41     0.10       frozenset({بيبسي, سكر, بيض})
42     0.10       frozenset({بيبسي, عدس, بيض})
43     0.10       frozenset({بيبسي, عدس, زيت})
44     0.10         frozenset({زيت, عدس, بيض})
45     0.10         frozenset({زيت, فول, بيض})
46     0.10  frozenset({زيت, بيبسي, عدس, بيض})

In [49]:
rules = association_rules(support , metric= 'confidence', min_threshold= 0.3)
rules = rules.sort_values('confidence', ascending= False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({بطاطس}),frozenset({فراخ}),0.1,0.20,0.1,1.000000,5.000000,1.0,0.080,inf,0.888889,0.500000,1.000000,0.750000
20,frozenset({فول}),frozenset({بيض}),0.1,0.20,0.1,1.000000,5.000000,1.0,0.080,inf,0.888889,0.500000,1.000000,0.750000
12,frozenset({جبنة قريش}),frozenset({بيض}),0.1,0.20,0.1,1.000000,5.000000,1.0,0.080,inf,0.888889,0.500000,1.000000,0.750000
9,frozenset({طعمية}),frozenset({بيبسي}),0.1,0.30,0.1,1.000000,3.333333,1.0,0.070,inf,0.777778,0.333333,1.000000,0.666667
76,"frozenset({بيبسي, زيت, بيض})",frozenset({عدس}),0.1,0.30,0.1,1.000000,3.333333,1.0,0.070,inf,0.777778,0.333333,1.000000,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,frozenset({بيبسي}),"frozenset({عدس, زيت})",0.3,0.10,0.1,0.333333,3.333333,1.0,0.070,1.350,1.000000,0.333333,0.259259,0.666667
65,frozenset({عدس}),"frozenset({زيت, بيض})",0.3,0.15,0.1,0.333333,2.222222,1.0,0.055,1.275,0.785714,0.285714,0.215686,0.500000
60,frozenset({عدس}),"frozenset({بيبسي, زيت})",0.3,0.10,0.1,0.333333,3.333333,1.0,0.070,1.350,1.000000,0.333333,0.259259,0.666667
85,frozenset({عدس}),"frozenset({بيبسي, زيت, بيض})",0.3,0.10,0.1,0.333333,3.333333,1.0,0.070,1.350,1.000000,0.333333,0.259259,0.666667
84,frozenset({بيبسي}),"frozenset({عدس, زيت, بيض})",0.3,0.10,0.1,0.333333,3.333333,1.0,0.070,1.350,1.000000,0.333333,0.259259,0.666667